//LOGIN
export const LOGIN_REQUEST = "@@auth/LOGIN_REQUEST";
export const LOGIN_SUCCESS = "@@auth/LOGIN_SUCCESS";
export const LOGIN_FAIL = "@@auth/LOGIN_FAIL";

export const LOGOUT_SUCCESS = "@@auth/LOGOUT_SUCCESS";

//TYPE
export const GET_TYPE_SUCCESS = "@@type/GET_TYPE_SUCCESS";
export const GET_GENERAL_EQUIPMENT_TYPE_SUCCESS =
  "@@type/GET_GENERAL_EQUIPMENT_TYPE_SUCCESS";

//EQUIPMENT
export const UPDATE_EQUIPMENT = "@@equip/UPDATE_EQUIPMENT";
export const ADD_EQUIPMENT = "@@equip/ADD_EQUIPMENT";
export const REMOVE_EQUIPMENT = "@@equip/REMOVE_EQUIPMENT";
export const EQUIPMENTS_LIST_SUCCESS = "@@equip/EQUIPMENTS_LIST_SUCCESS";
export const LIST_SUPPLIER_EQUIPMENT_SUCCESS =
  "@@equip/LIST_SUPPLIER_EQUIPMENT_SUCCESS";
export const LIST_REQUESTER_EQUIPMENT_SUCCESS =
  "@@equip/LIST_REQUESTER_EQUIPMENT_SUCCESS";
export const CLEAR_SEARCH_RESULT = "@@equip/CLEAR_SEARCH_RESULT";

//EQUIPMENT DETAIL
export const GET_EQUIPMENT_DETAIL_SUCCESS =
  "@@equip/GET_EQUIPMENT_DETAIL_SUCCESS";

//TRANSACTION
export const SEND_TRANSACTION_REQUEST_SUCCESS =
  "@@transaction/SEND_REQUEST_SUCCESS";
export const APPROVE_TRANSACTION_SUCCESS =
  "@@transaction/APPROVE_TRANSACTION_SUCCESS";
export const DENY_TRANSACTION_SUCCESS =
  "@@transaction/DENY_TRANSACTION_SUCCESS";
export const CANCEL_TRANSACTION_SUCCESS =
  "@@transaction/CANCEL_TRANSACTION_SUCCESS";

//TRANSACTION DETAIL
export const GET_TRANSACTION_DETAIL_SUCCESS =
  "@@equip/GET_TRANSACTION_DETAIL_SUCCESS";
export const CLEAR_TRANSACTION_DETAIL = "@@equip/CLEAR_TRANSACTION_DETAIL";

//SEARCH EQUIPMENT
export const SEARCH_EQUIPMENT_SUCCESS = "@@equip/SEARCH_EQUIPMENT_SUCCESS";

//CART
export const ADD_NEW_CART = "@@cart/ADD_NEW_CART";
export const UPDATE_CART = "@@cart/UPDATE_CART";
export const REMOVE_ITEM_CART = "@@cart/REMOVE_ITEM_CART";
export const REMOVE_CART = "@@cart/REMOVE_CART";

// STATUS
export const STATUS_LOADING = "@@status/LOADING";
export const STATUS_SUCCESS = "@@status/SUCCESS";
export const STATUS_FAIL = "@@status/FAIL";
