//LOGIN
export const LOGIN_REQUEST = "@@auth/LOGIN_REQUEST";
export const LOGIN_SUCCESS = "@@auth/LOGIN_SUCCESS";
export const LOGIN_FAIL = "@@auth/LOGIN_FAIL";

export const LOGOUT_SUCCESS = "@@auth/LOGOUT_SUCCESS";

//EQUIPMENT
export const UPDATE_EQUIPMENT = "@@equip/UPDATE_EQUIPMENT";
export const ADD_EQUIPMENT = "@@equip/ADD_EQUIPMENT";
export const REMOVE_EQUIPMENT = "@@equip/REMOVE_EQUIPMENT";
export const EQUIPMENTS_LIST_SUCCESS = "@@equip/EQUIPMENTS_LIST_SUCCESS";
export const LIST_SUPPLIER_EQUIPMENT_SUCCESS =
  "@@equip/LIST_SUPPLIER_EQUIPMENT_SUCCESS";
export const LIST_REQUESTER_EQUIPMENT_SUCCESS =
  "@@equip/LIST_REQUESTER_EQUIPMENT_SUCCESS";

//EQUIPMENT DETAIL
export const GET_EQUIPMENT_DETAIL_SUCCESS =
  "@@equip/GET_EQUIPMENT_DETAIL_SUCCESS";

//SEARCH EQUIPMENT
export const SEARCH_EQUIPMENT_SUCCESS = "@@equip/SEARCH_EQUIPMENT_SUCCESS";

//CART
export const ADD_NEW_CART = "@@cart/ADD_NEW_CART";
export const UPDATE_CART = "@@cart/UPDATE_CART";
export const REMOVE_ITEM_CART = "@@cart/REMOVE_ITEM_CART";
export const REMOVE_CART = "@@cart/REMOVE_CART";
