export const constructionActionTypes = {
  CONSTRUCTION_ALL_REQUEST: 'CONSTRUCTION_ALL_REQUEST',
  CONSTRUCTION_ALL_SUCCESS: 'CONSTRUCTION_ALL_SUCCESS',
  CONSTRUCTION_ALL_FAILURE: 'CONSTRUCTION_ALL_FAILURE',
}
