export const equipmentTypeCategoryActionTypes = {
  EQUIPMENT_TYPE_CATEGORY_ALL_REQUEST: 'EQUIPMENT_TYPE_CATEGORY_ALL_REQUEST',
  EQUIPMENT_TYPE_CATEGORY_ALL_SUCCESS: 'EQUIPMENT_TYPE_CATEGORY_ALL_SUCCESS',
  EQUIPMENT_TYPE_CATEGORY_ALL_FAILURE: 'EQUIPMENT_TYPE_CATEGORY_ALL_FAILURE',
}
