export const materialCartActionTypes = {
  MATERIAL_CART_CLEAR: 'MATERIAL_CART_CLEAR',
  MATERIAL_CART_ITEM_ADD: 'MATERIAL_CART_ITEM_ADD',
  MATERIAL_CART_ITEMS_REMOVE: 'MATERIAL_CART_ITEMS_REMOVE',
  MATERIAL_CART_ITEM_REMOVE: 'MATERIAL_CART_ITEM_REMOVE',
  MATERIAL_CART_ITEM_UPDATE: 'MATERIAL_CART_ITEM_UPDATE',
};
