export const authActionTypes = {
  REGISTER_REQUEST: 'USERS_REGISTER_REQUEST',
  REGISTER_SUCCESS: 'USERS_REGISTER_SUCCESS',
  REGISTER_FAILURE: 'USERS_REGISTER_FAILURE',

  LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
  LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
  LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',
  
  LOGOUT: 'USERS_LOGOUT',

  GETALL_REQUEST: 'USERS_GETALL_REQUEST',
  GETALL_SUCCESS: 'USERS_GETALL_SUCCESS',
  GETALL_FAILURE: 'USERS_GETALL_FAILURE',

  DELETE_REQUEST: 'USERS_DELETE_REQUEST',
  DELETE_SUCCESS: 'USERS_DELETE_SUCCESS',
  DELETE_FAILURE: 'USERS_DELETE_FAILURE',

  LOAD_USER_SUCCESS: 'LOAD_USER_SUCCESS',
  LOAD_USER_FAILURE: 'LOAD_USER_FAILURE',

  LOGIN_MODAL_SHOW: 'LOGIN_MODAL_SHOW',
  LOGIN_MODAL_HIDE: 'LOGIN_MODAL_HIDE',
  LOGIN_MODAL_TOGGLE: 'LOGIN_MODAL_TOGGLE',

  MIN_NOTIFICATIONS_COUNT: 'MINUS_NOTIFICATIONS_COUNT',
  ADD_NOTIFICATIONS_COUNT: 'ADD_NOTIFICATIONS_COUNT',
  SET_NOTIFICATIONS_COUNT: 'SET_NOTIFICATIONS_COUNT',

  VERIFYING_IMAGES_REQUEST: 'VERIFYING_IMAGES_REQUEST',
  VERIFYING_IMAGES_SUCCESS: 'VERIFYING_IMAGES_SUCCESS',
  VERIFYING_IMAGES_FAILURE: 'VERIFYING_IMAGES_FAILURE',
  VERIFYING_IMAGES_SET: 'VERIFYING_IMAGES_SET',
};
