export const TRANSACTION_STATUSES = {
  ACCEPTED: 'ACCEPTED',
  DENIED: 'DENIED',
  PENDING: 'PENDING',
  PROCESSING: 'PROCESSING',
  CANCELED: 'CANCELED',
  FINISHED: 'FINISHED',
  WAITING_FOR_RETURNING: 'WAITING_FOR_RETURNING'
};
