insert into admin_user(name, is_male, phone, email, role_id) VALUES ('kiet', true, '0971788779', 'truongtokiet@gmail.com', 1)
insert into admin_user(name, is_male, phone, email, role_id) VALUES ('khanh', true, '0971788779', 'kieutrongkhanh@gmail.com', 1)
insert into admin_user(name, is_male, phone, email, role_id) VALUES ('hung', true, '0971788779', 'truongtokiet@gmail.com', 2)
insert into admin_user(name, is_male, phone, email, role_id) VALUES ('hoang', true, '0971788779', 'tronghoang@gmail.com', 2)
insert into admin_user(name, is_male, phone, email, role_id) VALUES ('linh duc', false, '0000000000', 'linhduc@gmail.com', 2)
insert into admin_user(name, is_male, phone, email, role_id) VALUES ('gia huy', true, '0168831031', 'giahuy@gmail.com', 2)
insert into admin_user(name, is_male, phone, email, role_id) VALUES ('phu khanh', false, '0168831032', 'linhduc@gmail.com', 2)

insert into admin_account(username, password, account_id) VALUES ('admin', 'abc', 1)
insert into admin_account(username, password, account_id) VALUES ('admin2', 'abc', 2)
insert into admin_account(username, password, account_id) VALUES ('staff', '123', 3)
insert into admin_account(username, password, account_id) VALUES ('staff2', '123', 4)
insert into admin_account(username, password, account_id) VALUES ('staff3', '123', 5)
insert into admin_account(username, password, account_id) VALUES ('staff4', '123', 6)
insert into admin_account(username, password, account_id) VALUES ('staff5', '123', 7)

insert into general_equipment_type(name) VALUES ('Truck')
insert into general_equipment_type(name) VALUES ('Car')
insert into general_equipment_type(name) VALUES ('Spoon')
insert into general_equipment_type(name) VALUES ('Book')

insert into equipment_type(name, general_equipment_type_id) VALUES ('Xe Ben', 1)
insert into equipment_type(name, general_equipment_type_id) VALUES ('Xe Tai', 1)
insert into equipment_type(name, general_equipment_type_id) VALUES ('Xe Ban Tai', 1)
insert into equipment_type(name, general_equipment_type_id) VALUES ('Xe Cho Hang', 1)

insert into equipment_type(name, general_equipment_type_id) VALUES ('BWM', 2)
insert into equipment_type(name, general_equipment_type_id) VALUES ('Audi', 2)
insert into equipment_type(name, general_equipment_type_id) VALUES ('Mecedes', 2)
insert into equipment_type(name, general_equipment_type_id) VALUES ('BWM', 2)
insert into equipment_type(name, general_equipment_type_id) VALUES ('Audi', 2)
insert into equipment_type(name, general_equipment_type_id) VALUES ('Mecedes', 2)
insert into equipment_type(name, general_equipment_type_id) VALUES ('BWM', 2)
insert into equipment_type(name, general_equipment_type_id) VALUES ('Audi', 2)
insert into equipment_type(name, general_equipment_type_id) VALUES ('Mecedes', 2)
insert into equipment_type(name, general_equipment_type_id) VALUES ('BWM', 2)
insert into equipment_type(name, general_equipment_type_id) VALUES ('Audi', 2)
insert into equipment_type(name, general_equipment_type_id) VALUES ('Mecedes', 2)
