export const routeConsts = {
  HOME: 'HOME',
  LOGIN: 'LOGIN',
  SIGNUP: 'SIGNUP',

  PROFILE: 'PROFILE',
  PROFILE_CONTRACTOR: 'PROFILE_CONTRACTOR',
  NOTIFICATIONS: 'NOTIFICATIONS',

  // Construction
  CONSTRUCTIONS: 'CONSTRUCTIONS',
  CONSTRUCTION_ADD: 'CONSTRUCTION_ADD',

  // Equipment
  EQUIPMENTS: 'EQUIPMENTS',
  EQUIPMENT_DETAIL: 'EQUIPMENT_DETAIL',
  EQUIPMENT_MY: 'EQUIPMENT_MY',
  EQUIPMENT_ADD: 'EQUIPMENT_ADD',
  EQUIPMENT_EDIT: 'EQUIPMENT_EDIT',
  EQUIPMENT_SUPPLY: 'EQUIPMENT_SUPPLY',
  EQUIPMENT_TRANSACTION_DETAIL: 'EQUIPMENT_TRANSACTION_DETAIL',
  EQUIPMENT_REQUEST: 'EQUIPMENT_REQUEST',
  EQUIPMENT_REQUEST_DETAIL: 'EQUIPMENT_REQUEST_DETAIL',

  // Material
  MATERIALS: 'MATERIALS',
  MATERIAL_CART: 'MATERIAL_CART',
  MATERIAL_DETAIL: 'MATERIAL_DETAIL',
  MATERIAL_MY: 'MATERIAL_MY',
  MATERIAL_MY_DETAIL: 'MATERIAL_MY_DETAIL',
  MATERIAL_ADD: 'MATERIAL_ADD',
  MATERIAL_EDIT: 'MATERIAL_EDIT',
  MATERIAL_TRANSACTION_DETAIL: 'MATERIAL_TRANSACTION_DETAIL',
  MATERIAL_SUPPLY: 'MATERIAL_SUPPLY',
  MATERIAL_REQUEST: 'MATERIAL_REQUEST',
  MATERIAL_REQUEST_DETAIL: 'MATERIAL_REQUEST_DETAIL',

  // Debris
  DEBRISES: 'DEBRISES',
  DEBRIS_DETAIL: 'DEBRIS_DETAIL',
  DEBRIS_MY: 'DEBRIS_MY',
  DEBRIS_ADD: 'DEBRIS_ADD',
  DEBRIS_EDIT: 'DEBRIS_EDIT',
  DEBRIS_SUPPLY: 'DEBRIS_SUPPLY',
  DEBRIS_SUPPLY_STATUS: 'DEBRIS_SUPPLY_STATUS',
  DEBRIS_SUPPLY_DETAIL: 'DEBRIS_SUPPLY_DETAIL',
  DEBRIS_REQUEST: 'DEBRIS_REQUEST',
  DEBRIS_REQUEST_STATUS: 'DEBRIS_REQUEST_STATUS',
  DEBRIS_REQUEST_DETAIL: 'DEBRIS_REQUEST_DETAIL',

  // Subscription
  SUBSCRIPTION_REQUEST: "SUBSCRIPTION_REQUEST",
  SUBSCRIPTION_ADD: "SUBSCRIPTION_ADD",
};
